import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const ROOT = path.resolve(__dirname, "..");
const MODELS_PATH = path.join(ROOT, "prisma", "schema.models.prisma");
const OUTPUT_PATH = path.join(ROOT, "prisma", "schema.prisma");

// --- Header templates ---

const SQLITE_HEADER = `// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Source: prisma/schema.models.prisma
// Generated by: npm run schema:sqlite

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
`;

const POSTGRES_HEADER = `// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Source: prisma/schema.models.prisma
// Generated by: npm run schema:postgres

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema"]
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
  schemas   = ["devflow"]
}
`;

// --- Transform logic ---

function addSchemaAnnotations(models: string, schemaName: string): string {
  const lines = models.split("\n");
  const result: string[] = [];
  let insideModel = false;
  let braceDepth = 0;

  for (const line of lines) {
    // Detect model block start
    if (/^model\s+\w+\s*\{/.test(line)) {
      insideModel = true;
      braceDepth = 1;
      result.push(line);
      continue;
    }

    if (insideModel) {
      // Track nested { }
      for (const ch of line) {
        if (ch === "{") braceDepth++;
        if (ch === "}") braceDepth--;
      }

      // Reached closing } of model block
      if (braceDepth === 0) {
        // Add @@schema if not already present
        if (!result.some((l, i) => i > result.length - 5 && l.includes("@@schema"))) {
          result.push(`  @@schema("${schemaName}")`);
        }
        result.push(line); // closing }
        insideModel = false;
        continue;
      }
    }

    result.push(line);
  }

  return result.join("\n");
}

function removeSchemaAnnotations(models: string): string {
  return models
    .split("\n")
    .filter((line) => !line.trim().startsWith("@@schema("))
    .join("\n");
}

// --- Main ---

const target = process.argv[2];

if (!target || !["sqlite", "postgres"].includes(target)) {
  console.error("Usage: tsx scripts/generate-prisma-schema.ts <sqlite|postgres>");
  process.exit(1);
}

if (!fs.existsSync(MODELS_PATH)) {
  console.error(`[generate-schema] Model file not found: ${MODELS_PATH}`);
  process.exit(1);
}

const modelsRaw = fs.readFileSync(MODELS_PATH, "utf-8");

let output: string;
if (target === "postgres") {
  output = POSTGRES_HEADER + "\n" + addSchemaAnnotations(modelsRaw, "devflow");
} else {
  output = SQLITE_HEADER + "\n" + removeSchemaAnnotations(modelsRaw);
}

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`[generate-schema] Generated schema.prisma for ${target}`);

// Validate with prisma format
try {
  execSync("npx prisma format", { cwd: ROOT, stdio: "pipe" });
  console.log(`[generate-schema] Validation passed`);
} catch (err) {
  console.error(`[generate-schema] Generated schema has format issues:`);
  console.error((err as { stderr?: Buffer }).stderr?.toString() ?? "Unknown error");
  process.exit(1);
}
